name: Reusable workflow

on:
  workflow_call:
    inputs:
      os:
        description: "Operating system to run on"
        default: "ubuntu-latest"
        required: false
        type: string
      nixpkgs-commit:
        description: "Nixpkgs commit to use"
        default: ""
        required: false
        type: string

jobs:
  check:
    name: Check
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          NIX_ARGS=("flake" "check" "--print-build-logs")
          if [[ -n "${{ inputs.nixpkgs-commit }}" ]]; then
            NIX_ARGS+=("--override-input" "nixpkgs" "github:NixOS/nixpkgs/${{ inputs.nixpkgs-commit }}")
          fi
          NIX_ARGS+=(".#")
          nix "${NIX_ARGS[@]}"

  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          NIX_ARGS=("build" "--print-build-logs")
          if [[ -n "${{ inputs.nixpkgs-commit }}" ]]; then
            NIX_ARGS+=("--override-input" "nixpkgs" "github:NixOS/nixpkgs/${{ inputs.nixpkgs-commit }}")
          fi
          NIX_ARGS+=(".#")
          nix "${NIX_ARGS[@]}"

  run:
    name: Run for CUDA ${{ matrix.cuda-version }}
    needs: build
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        cuda-version:
          - "11.4.4"
          - "11.5.2"
          - "11.6.2"
          - "11.7.1"
          - "11.8.0"
          - "12.0.1"
          - "12.1.1"
          - "12.2.2"
    env:
      CUDA_REDIST_MANIFEST: redistrib_${{ matrix.cuda-version }}.json
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: mkdir -p ./manifests
      - run: |
          curl \
            --location "https://developer.download.nvidia.com/compute/cuda/redist/${{ env.CUDA_REDIST_MANIFEST }}" \
            --output "./manifests/${{ env.CUDA_REDIST_MANIFEST }}"
      - run: |
          NIX_ARGS=("run" "--print-build-logs")
          if [[ -n "${{ inputs.nixpkgs-commit }}" ]]; then
            NIX_ARGS+=("--override-input" "nixpkgs" "github:NixOS/nixpkgs/${{ inputs.nixpkgs-commit }}")
          fi
          NIX_ARGS+=(".#" "--" "--cleanup" "--no-parallel" "./manifests/${{ env.CUDA_REDIST_MANIFEST }}")
          nix "${NIX_ARGS[@]}"
      - uses: actions/upload-artifact@v3
        with:
          name: manifests_${{ inputs.nixpkgs-commit != '' && inputs.nixpkgs-commit || 'lock' }}
          path: ./manifests/
